--------------------------------------------------------------------------------
-- Library: object.e
--------------------------------------------------------------------------------
-- Notes:
--
--
--------------------------------------------------------------------------------
--/*
--= OOEU Library for the Object Class
------
--[[[Version: 1.3.0
--OOEU Versions: 1.9.0 and later
--Author: C A Newbould
--Date: 2021.01.19
--Status: operational; incomplete
--Changes:]]]
--* ##equals## (**Object**) defined
--
------
--==OOEU core library: object.e
--
-- The following summary gives a short-form indication of the contents of this
-- module.
--
--===Classes (methods)
--* **Object**
--** ##equals##(o) : b
--** ##show##([s])
--
-- Utilise these features
-- by adding the following statement to your module:
--<eucode>include object.e</eucode>
--
------
--*/
--------------------------------------------------------------------------------
--/*
--==Interface
--*/
--------------------------------------------------------------------------------
--/*
--=== Includes
--*/
--------------------------------------------------------------------------------
include core.e -- for basic utilities & type definitions
--------------------------------------------------------------------------------
--
--=== Constants
--
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--
--=== Euphoria types
--
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--
--=== Variables
--
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--
--=== Routines
--
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--/*
--=== Classes
--*/
--------------------------------------------------------------------------------
global euclass Object(object self) -- the base (anonymous) class
    function equals(object other) : boolean
        return equal(this, other)
    end function
    procedure show()
        ?this
    end procedure
    procedure show(sequence format)
        printf(1, format, {this})
    end procedure
end euclass
--------------------------------------------------------------------------------
--/*
--====Property
--<eucode>object this</eucode>
--====Methods
--<eucode>function equals(object other) : boolean -- TRUE if the same
--<eucode>show([sequence format]) -- displays the Object's property value
-- either prettily or via a format specifier </eucode>
--*/
--------------------------------------------------------------------------------
--==== Defined instances
--
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Previous versions
--------------------------------------------------------------------------------
--[[[Version: 1.2.0
--OOEU Versions: 1.9.0 and later
--Author: C A Newbould
--Date: 2020.08.05
--Status: operational; incomplete
--Changes:]]]
--* ##show## extended
--------------------------------------------------------------------------------
--[[[Version: 1.1.0
--OOEU Versions: 1.9.0 and later
--Author: C A Newbould
--Date: 2020.08.05
--Status: operational; incomplete
--Changes:]]]
--* moved core Euphoria material to //core.e//
--------------------------------------------------------------------------------
--[[[Version: 1.0.0
--OOEU Versions: 1.9.0 and later
--Author: C A Newbould
--Date: 2020.08.04
--Status: operational; incomplete
--Changes:]]]
--* created
--* //TRUE// and //FALSE// defined
--* **boolean** defined
--* ##iif## defined
--* **Object** defined
--* ##show## (**Object**) defined
--------------------------------------------------------------------------------
